function [nc,I,J,K,Dx,Dy,Dz,varargout] = matrixV3V(path)
% This code organizes a text file (Tecplot format) in Matlab matrix
% format.
% Created by Ricardo Mejia-Alvarez. Urbana, IL. 03/03/08
% modified: 07/10/08
% modified: 11/14/08
% modified: 09/29/09
%
% input:
% path: full path for the file to analyze
%
% outputs:
% nc: number of columns in the file, which will be the number of matrices
% generated by this function
% I: number of columns in the matrices
% J: number of rows in the matrices
% Dx and Dy: grid spacings in each coordinate
%
%
% V3V PIV:      varargout(1) => X coordinate
%               varargout(2) => Y coordinate
%               varargout(3) => Z coordinate
%               varargout(4) => U
%               varargout(5) => V
%               varargout(6) => W
%               varargout(7) => CHC
%
% For other kind of files, these parameters are user defined

%m = fopen(path,'r');      %open the file selected
%
%fgets(m);  %discards all the characters before the numerical data.
%first = fgets(m);   %reads the first line of data
%first = str2num(first); %#ok<ST2NM>
%nc = length(first); %calculates the number of columns in the files
%                                            
%C = textscan(m,'%f64','delimiter',','); %reads the numerical data from the file
%A = C{:};     %saves the data in a vector
%A = [first' ; A];
%
%A = reshape(A,nc,length(A)/nc)';

A = importdata(path);
header = A.textdata;
A = A.data;
nc = size(A,2);

I = find(A(1,1)-A(2:end,1) == 0, 1);
Dx = abs(A(1,1) - A(2,1));

A = sortrows(A,[3,1,2]);
J = find(A(1,2)-A(2:end,2) == 0, 1);
Dy = abs(A(1,2) - A(2,2));

% Reorganize the File
A = sortrows(A,[3,2,1]);

K = length(A(:,1))/(I*J);
Dz = abs(A(1,3) - A(I*J+1,3));

varargout = cell(1,nc);

A = sortrows(A,[3,1,2]);
for k = 1 : nc
    U = reshape(A(:,k),J,I,K);
    varargout(k) = {U};
end